controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

posts:
    path: /api/posts/
    controller: App\Controller\PostController::getAllPosts